name: Generate GitHub Stat Cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Stats Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-stats.svg
          base: header, activity, community, repositories, metadata
          plugin_lines: no
          output_action: none

      - name: Move SVG to Workspace
        run: |
          sudo cp /metrics_renders/github-stats.svg ./github-stats.svg
          sudo chown $USER:$USER ./github-stats.svg

      - name: Commit and Push SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update github stats svg"
          file_pattern: "github-stats.svg"
